### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by arunkumar2687** [thaiphan/magento2-s3#1]
Hi Thai,

I guess you missed the installation guide for this module. it redirects to the same github page.

**Comment by thaiphan** [comment]
Hey @arunkumar2687,

I was planning on writing the installation guide tonight! Will inform you when it's ready.

**Comment by shirsatsandeep** [comment]
Thanks for the module , It will good if you share installation guide.

**Comment by thaiphan** [comment]
Hey @shirsatsandeep,

Whoops, I forgot to tell you that I already wrote an installation guide a while ago. It's currently available on the [wiki](https://github.com/thaiphan/magento2-s3/wiki/Installation).

Regards,

Thai
