### ISSUE TITLE
Recall in another module

### ISSUE THREAD

**Issue by freezefeather** [thaiphan/magento2-s3#13]
Can give some example or which files I should refer if I want to recall the function in another module(e.g slider module)?

**Comment by thaiphan** [comment]
Hi @freezefeather,

If you can give more details on what you want to do, I can update the documentation to provide examples on how to do so.

Regards,

Thai

**Comment by thaiphan** [comment]
Hi @freezefeather,

You can just dependency in `\Magento\MediaStorage\Helper\File\Storage\Database` into whatever class you need and call all the standard functions. My plugin is smart enough to pick up that you're using S3 and sync accordingly.

Regards,

Thai
