### ISSUE TITLE
Customer headers for S3 objects

### ISSUE THREAD

**Issue by matrixbegins** [thaiphan/magento2-s3#14]
HI Just want to know, the setting customer headers like expiry etc is very common.
how can I do that using this extension? If not, can you please guide me for the piece of the code that is uploading the file,  I'll do necessary changes and submit a pull request.

**Comment by thaiphan** [comment]
Hi @matrixbegins,

I've added some config options to allow you to set the CacheControl and Expires headers in the latest version of this extension.

Regards,

Thai
