### ISSUE TITLE
Colour Swatch - Upload an image file

### ISSUE THREAD

**Issue by measureddesigns** [thaiphan/magento2-s3#16]
Hi,

I'm having an issue uploading image files for swatch colours when using the plugin. Uploading the file doesn't seem to work / save.

Disabling the plugin allows me to upload the file, although I now have synch issues as it's looking for it at cdn.mysite.com/attribute/swatch

I've had the problem on Magento 2.1.7 - 9.

Thanks

Andrew

**Comment by Karthikeyan23jan** [comment]
Hi, 
I have same issue in magento 2.1.3. Any solution????

**Comment by pranav-gaikwad** [comment]
Same happens with product place holder images also. Even if the module is enabled, Magento won't take these files from S3 links. Instead, it searches for files on disk.

**Comment by measureddesigns** [comment]
As a workaround to get swatch image files to show;

php bin/magento s3:storage:disable
php bin/magento indexer:reindex
php bin/magento cache:flush

Copy generated swatch images from live server.
Manually upload images directly to S3.
Then set back;
php bin/magento s3:storage:enable

**Comment by thaiphan** [comment]
Hey guys,

I've had a look. It looks like a bug in core Magento 2. I'll see what I can do from my side.

**Comment by thaiphan** [comment]
Hey guys,

I've pushed up a new version of my extension that should let you load colour swatches now. Enjoy!

Regards,

Thai
