### ISSUE TITLE
Table Flag doesn't exist on MAgento install due to custom cli command

### ISSUE THREAD

**Issue by maky13** [thaiphan/magento2-s3#19]
Hi,

I have a problem with Magento 2.1.8 during the install of MAgento when I have this module installed.
Basically the module add some cli command but not properly and so the install doesn't work.
I had the same kind of issue with the table "store_website" and here is the result of my investigation : 

> it occurs when you have added any new CLI command that ask (directly or not) for Magento\Framework\Locale\ResolverInterface.
> This Locale Resolver try in its constructor to init the local to use from the current website, but it makes a fall-back the default website if no website is already loaded.
> So, if any class ask for this Locale Resolver, it will directly try to load the default website when using the Magento CLI.
> But on the install, this default website does not exists yet => You will have the error.
> In my case, I was asking for Magento\Customer\Api\CustomerRepositoryInterface.
> So what you have to do, is to identify the asked class that indirectly ask for the Local Resolver, and to use its Factory instead.

Here is the diff I used on my issue, in order to help you :
```
diff --git a/app/code/Bug/Email/Console/Command/TestCommand.php b/app/code/Bug/Email/Console/Command/TestCommand.php
index 83aec04..22463fc 100644
--- a/app/code/Bug/Email/Console/Command/TestCommand.php
+++ b/app/code/Bug/Email/Console/Command/TestCommand.php
@@ -14,7 +14,9 @@ use Symfony\Component\Console\Input\InputInterface;
 use Symfony\Component\Console\Input\InputOption;
 use Symfony\Component\Console\Output\OutputInterface;
 use Magento\Framework\App\State as AppState;
+use Magento\Customer\Api\AccountManagementInterfaceFactory;
 use Magento\Customer\Api\AccountManagementInterface;
+use Magento\Customer\Api\CustomerRepositoryInterfaceFactory;
 use Magento\Customer\Api\CustomerRepositoryInterface;
 
 /**
@@ -26,33 +28,43 @@ use Magento\Customer\Api\CustomerRepositoryInterface;
 class TestCommand extends AbstractCommand
 {
     /**
+     * @var CustomerRepositoryInterfaceFactory
+     */
+    protected $customerRepositoryFactory;
+
+    /**
      * @var CustomerRepositoryInterface
      */
     protected $customerRepository;
 
     /**
+     * @var AccountManagementInterfaceFactory
+     */
+    protected $accountManagementFactory;
+
+    /**
      * @var AccountManagementInterface
      */
-    protected $customerAccountManagement;
+    protected $accountManagement;
 
     /**
      * TestCommand constructor.
      *
-     * @param AppState                    $appState
-     * @param CustomerRepositoryInterface $customerRepository
-     * @param AccountManagementInterface  $customerAccountManagement
-     * @param null                        $name
+     * @param AppState                           $appState
+     * @param CustomerRepositoryInterfaceFactory $customerRepositoryFactory
+     * @param AccountManagementInterfaceFactory  $accountManagementFactory
+     * @param null                               $name
      */
     public function __construct(
-        AppState                    $appState,
-        CustomerRepositoryInterface $customerRepository,
-        AccountManagementInterface  $customerAccountManagement,
+        AppState                           $appState,
+        CustomerRepositoryInterfaceFactory $customerRepositoryFactory,
+        AccountManagementInterfaceFactory  $accountManagementFactory,
         $name = null
     ) {
         parent::__construct($appState, $name);
 
-        $this->customerRepository        = $customerRepository;
-        $this->customerAccountManagement = $customerAccountManagement;
+        $this->customerRepositoryFactory = $customerRepositoryFactory;
+        $this->accountManagementFactory  = $accountManagementFactory;
     }
 
     /**
@@ -84,7 +96,6 @@ class TestCommand extends AbstractCommand
         parent::configure();
     }
 
-
     /**
      * Executes the current command.
      *
@@ -113,12 +124,12 @@ class TestCommand extends AbstractCommand
         $output->writeln('Customer Id ['.$customerId.']');
 
         // load the customer
-        $customer = $this->customerRepository->getById($customerId);
+        $customer = $this->getCustomerRepository()->getById($customerId);
         $output->writeln('Customer Email ['.$customer->getEmail().']');
 
         // send the email
         $output->writeln('Reset the Password');
-        $this->customerAccountManagement->initiatePasswordReset(
+        $this->getAccountManagement()->initiatePasswordReset(
             $customer->getEmail(),
             \Magento\Customer\Model\AccountManagement::EMAIL_REMINDER,
             $customer->getWebsiteId()
@@ -128,4 +139,32 @@ class TestCommand extends AbstractCommand
 
         return 0;
     }
+
+    /**
+     * Get the customer repository
+     *
+     * @return CustomerRepositoryInterface
+     */
+    protected function getCustomerRepository()
+    {
+        if ($this->customerRepository === null) {
+            $this->customerRepository = $this->customerRepositoryFactory->create();
+        }
+
+        return $this->customerRepository;
+    }
+
+    /**
+     * Get the account management
+     *
+     * @return AccountManagementInterface
+     */
+    protected function getAccountManagement()
+    {
+        if ($this->accountManagement === null) {
+            $this->accountManagement = $this->accountManagementFactory->create();
+        }
+
+        return $this->accountManagement;
+    }
 }
```
Concerning the stack trace, I have stopped my analysis where all the cli commands are initialised. I removed this module from composer and tried again and everything was working just fine after.
I don't know which one is the interface that induces the issue as the flag table is not used that much.

Best Regards,

**Comment by thaiphan** [comment]
Hey @maky13,

I'm sorry but I don't know how to reproduce the problem given the information that you provided me. 😢

Can you provide more details?

Regards,

Thai

**Comment by DavidLambauer** [comment]
I do have the same issue. I'll have a deeper look into that

**Comment by DavidLambauer** [comment]
By disabling command by command, I found out that the first defined commands work but there must an error in one of the following:

```xml
<item name="s3StorageDisableCommand" xsi:type="object">Thai\S3\Console\Command\StorageDisableCommand</item>
                <item name="s3StorageEnableCommand" xsi:type="object">Thai\S3\Console\Command\StorageEnableCommand</item>
                <item name="s3StorageExportCommand" xsi:type="object">Thai\S3\Console\Command\StorageExportCommand</item>
```

**Comment by z3r0f0x** [comment]
Looks like the issue is related to the factory classes in the use block not being present during a fresh install, since most (all?) of those are created after the installation is complete.

**Comment by thaiphan** [comment]
Hi @maky13, @DavidLambauer and @z3r0f0x,

Okay I finally got my head around the problem. I've managed to reproduce the problem in another extension, which I've made a fix to, and I'll see about making the fix to this extension this weekend.

Thanks for the heads up!

Regards,

Thai

**Comment by thaiphan** [comment]
Hey guys,

The latest version of my extension should now address this problem!

Regards,

Thai

**Comment by bsmitty42388** [comment]
Hi @thaiphan , can you please explain what the issue was and how you fixed it? We have run into it a couple times and haven't found a solution to it. 

Thank you!
Brandon

**Comment by thaiphan** [comment]
Hey @bsmitty42388,

During the initial installation, Magento will perform dependency injection into every available CLI command. Unfortunately, if one of your constructor dependencies has another dependency on a class that requires the store_website information to exist, Magento will derp out (because that table doesn't exist at this point).

The solution is to swap out with a "factory" class.

The following commit is how I fixed it:

https://github.com/thaiphan/magento2-s3/commit/3996df69c144e9d5e6958f868de93521c1582a72

Regards,

Thai
