### ISSUE TITLE
Instalation via composer

### ISSUE THREAD

**Issue by lukaszolszewski** [thaiphan/magento2-s3#2]
Hello,

When I installed the plugin via composer I got an exception. 

>  Could not find package thaiphan/magento2-s3 at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability 

Probably it's something wrong in configuration php package manager or installation instruction ;)

**Comment by thaiphan** [comment]
Hey @lukaszolszewski,

Yeah, I haven't tagged v1.0.0 for this repo yet! I'm still doing testing and adding finishing touchings before I'll do so.

I will inform when everything is ready.

Regards,

Thai

**Comment by hakikihacioglu** [comment]
Hi,

i can still not install the extension because of that error message. Is there any update on this? Or how can I install it without composer.

Thank you

**Comment by hakikihacioglu** [comment]
For all, who stuck installing via composer, naming the branch

sudo composer require thaiphan/magento2-s3 dev-master

did the trick

**Comment by crantron** [comment]
@thaiphan you can tag 0.0.1 , ... , 0.0.9, which would still allow us to install with composer without using `composer require thaiphan/magento2-s3 dev-master`

**Comment by thaiphan** [comment]
Hey guys,

I've set a tag for 1.0.0-RC so running `composer require` should now work (seeing how Magento 2 has a stability level of alpha for some reason).

Regards,

Thai
