### ISSUE TITLE
region is not valid

### ISSUE THREAD

**Issue by senrysaRanjeet** [thaiphan/magento2-s3#20]
You have not provided an S3 region. You can do so using our config script.

Getting the above error

**Comment by thaiphan** [comment]
HI @senrysaRanjeet,

If you read the instructions on the wiki, you'll see that you need to set the S3 region via the CLI:

https://github.com/thaiphan/magento2-s3/wiki/Installation#step-1-configure-magento-to-use-your-s3-bucket

Regards,

Thai
