### ISSUE TITLE
issue while s3 exporting 

### ISSUE THREAD

**Issue by senrysaRanjeet** [thaiphan/magento2-s3#22]
i have configured the s3 with magento but getting below error when running below command :
Command:
php bin/magento s3:storage:export

Error:
The AWS credentials you provided did not work. Please review your details and tr
y again. You can do so using our config script.

**Comment by thaiphan** [comment]
Hey @senrysaRanjeet,

Can you run `php bin/magento s3:config:list` and review that the values that you have entered are correct?

Regards,

Thai

**Comment by senrysaRanjeet** [comment]
Yes, the credential is valid and it's showing under config list but when i am trying to import and export the data is not working.

**Comment by senrysaRanjeet** [comment]
Hi @thaiphan ,
i have follow your step for installation, but file is not uploading into amazon s3.

1. Can you please explain the process.
2. And the CloudFront is important for this?
3. I am doing it in my localhost.

Please respond 

Thanks

**Comment by thaiphan** [comment]
Hi @senrysaRanjeet,

Is it not working because of the error message that you mentioned before?

> The AWS credentials you provided did not work. Please review your details and try again. You can do so using our config script.

That implies that your settings are wrong.

Regards,

Thai

**Comment by thaiphan** [comment]
Closed because @senrysaRanjeet indicated in #21 that he was now able to upload to S3.
