### ISSUE TITLE
Image is uplodaing to magento media as well

### ISSUE THREAD

**Issue by kushhot** [thaiphan/magento2-s3#23]
Hi Thai,

I have setup S3 properly and image are auto syncing in to S3 bucket but images are also uploading in magento media folder which must not be .

kindly help for the same.

**Comment by thaiphan** [comment]
Hey @kushhot,

This extension hooks into the Magento 2 database media storage functionality, which will download the images to the `media` folder by default. You should be able to safely delete the images **(although maybe take a backup beforehand)**.

Regards,

Thai
