### ISSUE TITLE
files not uploading despite saying it's uploading

### ISSUE THREAD

**Issue by rcdlopez** [thaiphan/magento2-s3#26]
I installed the extension and configured it. No error messages come up and when I run php bin/magento s3:storage:export it appears to be uploading everything however nothing uploads to the S3 bucket and when it is enabled, the images are still brought in from within the media folder. 

This extension doesn't work

**Comment by thaiphan** [comment]
Hey @rcdlopez,

> No error messages come up and when I run php bin/magento s3:storage:export it appears to be uploading everything however nothing uploads to the S3 bucket

Are you running the export on the same server that you are hosting your images? You need to run on the same server!

> when it is enabled, the images are still brought in from within the media folder.

This extension hooks into the Magento 2 database media storage functionality, which will download the images to the `media` folder by default as some sort of caching mechanism. If Magento 2 can find that you have the image in the `media` folder, it won't bother to download from S3.

You should be able to safely delete the images **(although maybe take a backup beforehand)**. You can also change your static media URL to point to S3 or CloudFront.

Regards,

Thai

**Comment by rcdlopez** [comment]
Of course I'm running it on the same server.

I figured it out myself but you should REALLY add instructions for setting
up permissions on S3. You don't mention anything about how to properly
setup permissions for the user being used to upload the images. I was
getting a 403 permission denied error on S3 because the extension requires
a user with proper permissions.

Can you please add instructions for this on the github page for other
people and also so I can further understand how you set it up on your own
Magento 2 install?

**Comment by thaiphan** [comment]
Hey @rcdlopez,

> I was getting a 403 permission denied error on S3 because the extension requires
a user with proper permissions.

Okay, I will see if I can make the error throw an exception if you get a 403 response from S3.

Regards,

Thai

**Comment by rcdlopez** [comment]
The files have been uploaded to the S3 but the files are still served from
the server. How do you fix this?

**Comment by thaiphan** [comment]
Hey @rcdlopez,

> The files have been uploaded to the S3 but the files are still served from
the server.

As I explained in https://github.com/thaiphan/magento2-s3/issues/26#issuecomment-350888780, Magento will try and re-download files from S3 and then load the images from your local file system. This is a built-in caching mechanism by Magento to improve performance.

You can change your static media URL to point to S3 or CloudFront if you never want Magento to hit your file system.

Regards,

Thai

**Comment by vijaydcyb** [comment]
Hi @rcdlopez

Could you please explain how you resolved 403 access denied issue.

I am facing the same issue. able to upload images from CLI with the same user which magento 2 admin runs the code.

**Comment by jigudo** [comment]
Hi @rcdlopez and @thaiphan 

I am getting 403 Forbidden - Access Denied errors in exception log while running Export command. I have set up s3 bucket with no public access and have user policy and bucket policy. Please let me know the proper s3 setup to prevent this.
