### ISSUE TITLE
Installation Done , But not working

### ISSUE THREAD

**Issue by shirsatsandeep** [thaiphan/magento2-s3#3]
Hi Thai,
I have install module using given steps. Magento2 admin showing everything about S3 module like AccessKey etc. But while select storage Amazon S3 then clicking synchronise , nothing happen(We were unable to synchronize one or more media files. Please refer to the log file for details). And also images are not store in S3 bucket while adding product. it there anything to do. 
Please help .

**Comment by thaiphan** [comment]
Hey @shirsatsandeep,

I don't recommend that you use admin panel to sync the images. If you have lots of images, the sync will time out and you'll get stuck with the error that you've mentioned (been contemplating removing the functionality before tagging v1.0.0).

Are you able to follow my instructions in the wiki and get back to me?

https://github.com/thaiphan/magento2-s3/wiki/Installation

Regards,

Thai

**Comment by shirsatsandeep** [comment]
Hey @thaiphan ,
Step 1: Configure Magento to use your S3 bucket

php bin/magento s3:config:set \
    --access-key-id=XXXXXXX \
    --secret-key=XXXXXXX \
    --bucket=XXXXXXX \
    --region=XXXXXXX

after this step ,
I got message.
You have successfully updated your S3 credentials.

then i run php bin/magento s3:storage:export
but still may bucket is showing nothing.

**Comment by thaiphan** [comment]
Hey @shirsatsandeep,

Did running `php bin/magento s3:storage:export` return any error messages?

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @shirsatsandeep,

I noticed that the version I had uploaded to Packagist was out of date. Are you able to update and see if the latest changes addresses your problem?

Regards,

Thai

**Comment by thaiphan** [comment]
Closing due to lack of response.

**Comment by rcdlopez** [comment]
I'm having this same issue

**Comment by rcdlopez** [comment]
I followed the instructions exactly and not error messages appear. After running php bin/magento s3:storage:export, the console says that it's uploading the files however nothing is being uploaded to the S3 bucket and once you enable it it continues to grab the images from the default media folder. Nothing is happening.

**Comment by vijaydcyb** [comment]
Hi @thaiphan ,

I have installed your extension and followed the steps mentioned in installation guide.
1] After running php bin/magento s3:storage:export, the console says that it's uploading the files but nothing is being uploaded to the S3 bucket.

2] I have tried to insert the images in static block from admin it throws the below error.

Error executing "PutObject" on "my bucket path"  AccessDenied (client):  etc

All credentials are fine and its working from CLI.

Could you please let me know the reason why it is not working as expected.

Thanks
