### ISSUE TITLE
Fetch product media url on frontend

### ISSUE THREAD

**Issue by spellmen** [thaiphan/magento2-s3#32]
Hi,
My product images are not loading from s3 bucket via cloud front url, instead it is loading from my pub media folder of orgin domain.

My product images are loading from htt://mydomain.com/pub/get.php/catalog/product/cache/75eed2686e01eb22cb4050b2f40ddf97/d/i/dish_1.png
I need to get from cloud front http://cloudfront.net/catalog/product/cache/75eed2686e01eb22cb4050b2f40ddf97/d/i/dish_1.png

Thanks in advance....

**Comment by pranavgaikwad** [comment]
This should help -
Enable URL rewrites from Magento admin panel. 

You also need to update your Base Static Url settings if you are using CDN to deliver media.

**Comment by spellmen** [comment]
thank you @pranavgaikwad . Will try that you said.

**Comment by adshrc** [comment]
@spellmen, you have to set the base-urls. I just updated the installation wiki, see [here](https://github.com/thaiphan/magento2-s3/wiki/Installation).

**Comment by thaiphan** [comment]
@spellmen hasn't followed up with @pranavgaikwad so I'm assuming that this issue is resolved.
