### ISSUE TITLE
Captcha is broken after module setup

### ISSUE THREAD

**Issue by jbokhari** [thaiphan/magento2-s3#34]
I followed the instructions on the wiki and tested product image by adding a new product. The image loads from my s3 bucket successfully. All other existing images appear to have worked.

My problem is regarding captcha. I'm using captcha on my user registration form and the image link appears broken at all times. I checked the source of an image that was broken and it appears in my pub/media/captcha/base folder on my server, however new images do not go to s3. 
EG pub/media/captcha/base/c6c8cc5ca22a308a0a4429b1f4d93fc6.png appears, but only old captcha images that existed when I ran s3:export are in my s3 bucket.

I'm not sure how this is supposed to work but it seems to be broken to me right now. Any suggestions?

**Comment by jbokhari** [comment]
If anyone has this problem, what I ended up doing is using a module that activates ReCaptcha

https://github.com/karliuka/m2.ReCaptcha

Its actually much better than the original captcha included in magento.

**Comment by thaiphan** [comment]
Hi @jbokhari,

The latest version of this extension will now upload CAPTCHA images to S3.

Regards,

Thai
