### ISSUE TITLE
Installing without composer?

### ISSUE THREAD

**Issue by benyanke** [thaiphan/magento2-s3#35]
We (unfortunately) are not using composer to install modules. Is there a way to install easily by hand?

**Comment by jbokhari** [comment]
Hey @benyanke the developer doesn't seem to be too active lately. I didn't work on the module but following Magento 2 module setup you *should* be able to install in a directory of your own using these steps:

1. Download the module using clone or download link. File will be `magento2-s3-master.zip`
2. Create the directory `<magento_dir>/app/code/Thai/S3/`
3. Extract `magento2-s3-master.zip` contents to above directory.
4. Continue [setup](https://github.com/thaiphan/magento2-s3/wiki/Installation) as if you just installed using `composer require thaiphan/magento2-s3`

The only problem is composer handles dependencies differently depending on the modules needs. In this case I think composer might be necessary and I have not tested this but 95% of modules work this way. I'd say try it on a development site and see if it works.

**Comment by thaiphan** [comment]
Hi @benyanke,

Sorry, Composer is the only way at the moment to install my extension. How do you normally install your other extensions?

I'm trying to get it hosted on Magento Connect but it's taking a while to get approved. I guess just keep refreshing Magento Connect until it shows up (might be a few months but).

Regards,

Thai

**Comment by thaiphan** [comment]
Closing this ticket since I can't help OP. :(
