### ISSUE TITLE
Delete pub/media folder 

### ISSUE THREAD

**Issue by mvaisberg** [thaiphan/magento2-s3#36]
Hi, i could integrate the media files with S3 and i saw on the frontend that the products images are loaded thought S3 but when i delete the web server pub/media folder the product move to show the placeholder default image of magento

**Before delete pub/media:**
![selection_060](https://user-images.githubusercontent.com/4543889/38165077-57ff0280-34e4-11e8-8119-2df3f8e109f4.jpg)

**After delete pub/media:**
![selection_059](https://user-images.githubusercontent.com/4543889/38164990-1bd43254-34e3-11e8-9a52-ba0c17e1ae18.jpg)

What am i doing wrong? i want to delete all web server local image storage

**Comment by mvaisberg** [comment]
I think that if you delete entere media folder that happend but if you just delete the content of media folder it works!

**Comment by thaiphan** [comment]
Hi @mvaisberg,

Are you still having problems with this? My first question would be are you routing your images through `pub/get.php`?

Regards,

Thai

**Comment by thaiphan** [comment]
Closing the ticket due to no response.
