### ISSUE TITLE
Magento Register User Form Captcha

### ISSUE THREAD

**Issue by ijaz-ali-magento-legend** [thaiphan/magento2-s3#43]
Hi,
Hope you are doing well.
I am using this extension for my client. This extension is working fine for catalog and product images. But at magento 2 customer registration form when I use captcha, captcha image path is taken from s3 but captcha image is creating at native file system.
Kindly advise me at this issue.
Looking forward for your response.
Regards,
Ijaz Ali

**Comment by thaiphan** [comment]
Hi @ijaz-ali-magento-legend,

Yeah, as explained in #34, this extension doesn't support CAPTCHA at the moment.

If you want to help out with building out the support, I'd very much appreciate it. Otherwise, there's no ETA on when I'll build out the support.

Regards,

Thai

**Comment by thaiphan** [comment]
Hi @ijaz-ali-magento-legend,

The latest version of this extension will now upload CAPTCHA images to S3.

Regards,

Thai
