### ISSUE TITLE
Magento 2.1.* Error on di:compile Serialize/Json Class does not exists

### ISSUE THREAD

**Issue by pinedamg** [thaiphan/magento2-s3#45]
Hi, First, I would like to give you my thanks for this great extension.

But I found an issue with Magento 2.1.10 version, and realized that is an issue with all Magento versions 2.1.*.

Step to reproduce:

1) Install this extension into Magento 2.1.* version
2) Run commands and on setup:di:compile you will get the error

> [ReflectionException]                                             
>   Class Magento\Framework\Serialize\Serializer\Json does not exist

Basically into the class Thai\S3\Model\MediaStorage\File\Storage\S3, is trying to use a class that does not exist on those Magento versions.

So, I added support for this, the fix is into the PR https://github.com/thaiphan/magento2-s3/pull/46

Thank you very much.

Regards.-

**Comment by thaiphan** [comment]
Hi @pinedamg,

Thanks for contributing. I very much appreciate it. I've merged this change into the develop branch and will make a release with it included soon.

I'm closing this ticket to reduce the clutter of issues.

Regards,

Thai
