### ISSUE TITLE
Install went fine but image not loading

### ISSUE THREAD

**Issue by smoi** [thaiphan/magento2-s3#47]
Hello,

I did the installation process (https://github.com/thaiphan/magento2-s3/wiki/Installation) and it went smooth, everything was uploaded on S3 and even if i upload a new image I see it on s3 but the images are not working from s3 on the frontend, it tries to load them from 

> get.php/catalog/product/cache/f073062f50e48eb0f0998593e568d857/w/h/wh09-purple_main.jpg

I've also tried to update _Base URL for User Media Files_ poiting to s3 but it still loads from get.php

I tried cleaning all caches and everything.

What can I check more?

Thanks

**Comment by thaiphan** [comment]
Hi @smoi,

Did you remember to enable S3 integration using...

`php bin/magento s3:storage:enable`

Also, have you tried turning on media URL rewrites?

Regards,

Thai

**Comment by smoi** [comment]
Hello Thai,

yes sure, I'm using the default nginx.conf inside the Magento 2 folder.

I've tried enabling the module both from the bin/magento and from the admin but still no luck

> http://dev.honiehbeauty.com/get.php/catalog/product/cache/f073062f50e48eb0f0998593e568d857/l/t/lt02.jpg

it goes 404

I've tried both adding the s3 url in the media settings not adding it and still it calls the get.php

What's the expected behavior?

**Comment by smoi** [comment]
I've tried both enabling from the admin and from the bin/magento but still no luck it always loads from get.php.

I've also tried to set the media base url with s3 url but it still use the get.php

What's the expected behavior?

**Comment by smoi** [comment]
i've enabled url rewrites from the admin and now it's working as expected, maybe you should add it to the installation guide
