### ISSUE TITLE
Can I use AWS IAM instance profile instead of using access key and secrets?

### ISSUE THREAD

**Issue by pandeybk** [thaiphan/magento2-s3#48]
Can I use AWS IAM instance profile instead of using access key and secrets? Also is it possible to set this value using env.  I am trying to run magento using docker, looks like we need to store aws credentials in docker image itself.

**Comment by cdaivs-onica** [comment]
Any answers to this? Were you able to test and confirm if this is possible?

**Comment by thaiphan** [comment]
Hey guys,

Sorry, it's not possible at this time. I wouldn't mind somebody helping out with this.

Regards,

Thai

**Comment by thaiphan** [comment]
Hi guys,

I've pushed a change to the 3.x branch that allows you to use IAM with this module.

Regards,

Thai
