### ISSUE TITLE
Credential is not applied

### ISSUE THREAD

**Issue by Sheshadria** [thaiphan/magento2-s3#49]
How can we check applied credential is valid or not. when I trying php bin/magento s3:config:set command it showing "s3:config:set [--access-key-id[="..."]] [--secret-key[="..."]] [--bucket[="..."]] [--region[="..."]]" but already I have configured through the admin panel.

As well I triggered php bin/magento s3:storage:export and php bin/magento s3:storage:enable command is not responding any kind of success message.

**Comment by thaiphan** [comment]
Hi @Sheshadria,

You need to provide parameters to `s3:config:set`. If you don't provide any then the CLI will provide suggestions.

Have you thought about using `s3:config:list`?

Regards,

Thai

**Comment by Sheshadria** [comment]
I am facing now this error.

**Comment by Sheshadria** [comment]
php bin/magento s3:storage:export
PHP Fatal error:  Uncaught Error: Class 'Aws\S3\S3Client' not found in /var/www/html/magento2/s4sstaging/app/code/Thai/S3/Console/Command/StorageExportCommand.php:81
Stack trace:
#0 /var/www/html/magento2/s4sstaging/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Thai\S3\Console\Command\StorageExportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/magento2/s4sstaging/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/magento2/s4sstaging/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Thai\S3\Console\Command\StorageExportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var in /var/www/html/magento2/s4sstaging/app/code/Thai/S3/Console/Command/StorageExportCommand.php on line 81

**Comment by thaiphan** [comment]
How did you install my extension? It looks like you're missing a dependency on the S3 library. Did you install using Composer?

**Comment by Sheshadria** [comment]
Thanks Thaiphan, 

I updated through composer now it's working :)
