### ISSUE TITLE
Media not displayed from CDN

### ISSUE THREAD

**Issue by pranav-gaikwad** [thaiphan/magento2-s3#5]
Hi, 
Thanks for making this module available. I installed it correctly. And, I was able to export media files to S3 using `bin/magnento s3:storage:export`  I am using CDN to serve media (with S3 as backend) and I have made changes to media url accordingly in store configuration. Yet, I am facing a strange issue when I enable the module using `bin/magento s3:storage:enable` None of the media files are served from CDN, instead,  magento is trying to look for media at this link `http://local.magento.com/get.php/wysiwyg/home/home-main.jpg` which is causing 404s. Expected link is `http://<my_cdn_url>/wysiwyg/home/home-main.jpg`

**Comment by tushardatar** [comment]
Hi Pranav,

Check if you have enabled `Use Web Server Rewrites` . 
Check by Go to Store - Configuration - Web - Search Engines Optimization - 
set `Use Web Server Rewrites`  to **Yes**

Cheers

**Comment by pranav-gaikwad** [comment]
Hi Tushar, 

Thanks for pointing that out.
