### ISSUE TITLE
Class 'Aws\S3\S3Client' not found

### ISSUE THREAD

**Issue by patrickang** [thaiphan/magento2-s3#6]
Hi, I have installed the package but when I try to enable the storage via s3:storage:enable, it gives me the following error
`Class 'Aws\S3\S3Client' not found in /var/www/html/app/code/Thai/S3/Console/Command/StorageEnableCommand.php:52`

**Comment by thaiphan** [comment]
Hi @patrickang,

Sorry for the late reply! Are you still planning on using my extension or you've given up?

My first guess would be that you have not installed the dependencies for the extension using `composer install`.

Regards,

Thai

**Comment by thaiphan** [comment]
Closing due to lack of response.

You can re-open if you still want assistance!
