### ISSUE TITLE
app:config:dump exporting sensitive information

### ISSUE THREAD

**Issue by chocolatethunder** [thaiphan/magento2-s3#62]
When running 
```bash
php bin/magento app:config:dump
```
The S3 access keys are being exported to the config.php and not env.php

This is causing deployment pipeline issues because config.php is supposed to be part of version control and env.php is not. Don't want to accidentally publish my AWS data to Github.

Additionally, I have also tried adding this to app/etc/di.xml file
```php
<type name="Magento\Config\Model\Config\TypePool">
   <arguments>
      <argument name="sensitive" xsi:type="array">
         <item name="thai_s3/general/access_key" xsi:type="string">1</item>
         <item name="thai_s3/general/secret_key" xsi:type="string">1</item>
      </argument>
   </arguments>
</type>
```
But it doesn't affect the config export.

**Comment by atishgoswami** [comment]
Hi @thaiphan,

Added PR #67 for this issue fix.

Regards,
Atish

**Comment by thaiphan** [comment]
Everybody can take advantage of @atishgoswami's changes in the latest version of the extension. Thanks a lot!
