### ISSUE TITLE
Folder contentmanager/content not saving

### ISSUE THREAD

**Issue by rdesharnais** [thaiphan/magento2-s3#66]
When I change an image that is stored in the pub/media/contentmanager/content/ it is saved in Magento but not in S3. Which in turn gives me a 404 error when reloading the image...

Thanks!

**Comment by thaiphan** [comment]
Hey @rdesharnais 

You need to `contentmanager` as an allowed resource in Magento 2. This can be done via a config file.

I have an example of what you need to do below:

https://github.com/magento/magento2/pull/12187

I hope that helps.

Regards,

Thai
