### ISSUE TITLE
After Sync

### ISSUE THREAD

**Issue by hammadxoho** [thaiphan/magento2-s3#7]
Kudos to you for this plugin.
I followed all your instructions and have been able to upload all the required files to my s3 server. I have also enable the storage for s3 in magento2. 
Still, all my images are currently coming from my own server and not from S3.. although everything is synced.

How can i point all the images to come from S3 rather than my server

Thanks

**Comment by FerihumF** [comment]
Hi @hammadxoho,
I was also searching for the solution, this did the trick:
Just enter your S3-Bucket Link in the Magento-Backend under Shop>Configuration>General>Web>Base Url for media files (e.g. "https://s3.eu-central-1.amazonaws.com/bucket-xyz/").

**Comment by hammadxoho** [comment]
Thank you for the help @FerihumF . i was able to find this and make the change.

**Comment by lopezchr** [comment]
Hi. I followed the instructions but at the end the images still served from magento and not from s3 service. I cleaned the cache and reindex the catalog but still not working. What can I do?

**Comment by hammadxoho** [comment]
@lopezchr did you make the changes suggested by @FerihumF ?

**Comment by lopezchr** [comment]
@hammadxoho  yes, I changed the media base path like @FerihumF said, flushed cache and reindex the catalog too. It can be an error of magento 2 configuration? I have to do any think after that?

**Comment by thaiphan** [comment]
Hey @lopezchr,

Sorry for the late reply. Are you still unable to load images from S3? Send me an email and I'll provide support.

Regards,

Thai

**Comment by thaiphan** [comment]
Closing issue. People can open new ones if problems persist.

**Comment by rcdlopez** [comment]
CAN YOU PLEASE EXPLAIN HOW YOU FIXED THIS? The images are still served from my server and not from the S3

**Comment by lopezchr** [comment]
Just reindex and clean cache from command line.
