### ISSUE TITLE
How can i used cloudfront for s3 bucket?

### ISSUE THREAD

**Issue by dineshmanne** [thaiphan/magento2-s3#71]
I want to know how can i use cloudfront for my s3 bucket? I created cloudfront url for my s3 bucket. Can i update this url in static files URL , Media URL under Configurations --> General --> Web ?? 

Please guide me on this.

**Comment by thaiphan** [comment]
Hey @dineshmanne 

Yeah, you can change the static media URL to be your CloudFront URL. You also need to configure your CloudFront to use S3 as an original server. Also don't forget to make sure all media images are being routed through `get.php` (which should be configured by default by Magento).

Regards,

Thai
