### ISSUE TITLE
magento2.3.0-s3

### ISSUE THREAD

**Issue by Kristopher-Mark-Mike** [thaiphan/magento2-s3#72]
I just added this to our Magento 2.3 site and it works like a charm!!!
Thank you for creating this!!!

**Comment by thaiphan** [comment]
Hey @Kristopher-Mark-Mike 

Thanks man! It makes it worthwhile that people are enjoying my plugin. Lots of people just send angry emails because they can't get it to work. 😭

Feel free to post an issue here if you come across anything.

Regards,

Thai
