### ISSUE TITLE
MimeType Issue

### ISSUE THREAD

**Issue by hammadxoho** [thaiphan/magento2-s3#8]
Hey,

I have been running into an issue with this plugin. It gets installed and everything is fine and alright. Problem is when i open a product page, i sometimes get an empty page with an image in between, specially on chrome browser.
i get the following in console.
Resource interpreted as Document but transferred with MIME type image/jpeg:

I tried disabling all the extension i have installed one by one.. and this is the one which was causing the issue

Can you please let me know where i went wrong. I am currently debugging it myself as well.

I will let you know if i come up with something

Thanks

**Comment by thaiphan** [comment]
Hey @hammadxoho,

Sorry for the late reply! I dunno if you're still trying to resolve this problem. However, if you are, can you post some screenshots?

**Comment by thaiphan** [comment]
Closing because of lack of response. I don't have enough information to action this.
