### ISSUE TITLE
Not Able to Enable or Export Due to Errors

### ISSUE THREAD

**Issue by pareshpa** [thaiphan/magento2-s3#9]
I have installed the extension and configured the configurations below. 
1. Access Key
2. Secret Key
3. Bucket
4. Region

Also, I have also installed the AWS Library using **composer require aws/aws-sdk-php** and the version of AWS library is 3.0.

After configured the extension, I have tried to run the enable / export command but I am always getting the error below.

"The AWS credentials you provided did not work. Please review your details and try again. You can do so using our config script."

**Comment by thaiphan** [comment]
Hey @pareshpa,

Here are some tips to address the problem:

- Does the bucket exist yet in S3?
- Is the bucket in a different region to what you've set?

Let me know how you go!

**Comment by vineeth-relevance-0383** [comment]
Hi Thaiphan,

I have tried to integrate the extension but 
bin/magento s3:storage:export
bin/magento s3:storage:enable

These 2 option while executing it is throwing "The AWS credentials you provided did not work. Please review your details and try again. You can do so using our config script." 
I have verified from the admin panel whether the keys are correct or not. Everything was perfect but I couldn't understand why I am getting this error even if my credentials are correct.  My secret key contains "/" is that creating problem if it is how can I fix that . I have tried in Magento 2.1.4 and Magento 2.0.14.

**Comment by measureddesigns** [comment]
Hi,

I'm having the same issue using Magento 2.1.7 and thaiphan/magento2-s3.

The keys and region are correct, the user has AWS S3 access and the S3 bucket exists.

Do I need to define the user as part of the script?

Thanks

Andrew

**Comment by measureddesigns** [comment]
Ok, I found the issue. I was using using the full Amazon bucket name, not the title

Doesn't work
 --bucket=MySiteName.com.s3.amazonaws.com.

Works
--bucket=MySiteName.com

**Comment by thaiphan** [comment]
Hi everybody,

I advise that you all follow @measureddesigns tip and set the bucket to be just your unique identifier and now the full URL.

Regards,

Thai
